Update query-upgrade-23-24.md
wallabag/doc pull request #141
Opened 2021-01-19 19:50 UTC by jonathansada

Added "wallabag_" to the tables on the SQLite update script

2021-01-21 08:43 UTC, j0k3r requested changes

2021-01-21 08:43 UTC, j0k3r commented on en/admin/query-upgrade-23-24.md
> +CREATE TEMPORARY TABLE __temp__user AS SELECT id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, name, cr
```suggestion
CREATE TEMPORARY TABLE __temp__user AS SELECT id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, name, created_at, updated_at, authCode, twoFactorAuthentication FROM wallabag_user;
```

2021-01-21 08:43 UTC, j0k3r commented on en/admin/query-upgrade-23-24.md
> +INSERT INTO  wallabag_user (id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, name, created_at, updated_
```suggestion
INSERT INTO  wallabag_user (id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, name, created_at, updated_at, authCode, emailTwoFactor) SELECT id, username, username_canonical, email, email_canonical, enabled, salt, password, last_login, confirmation_token, password_requested_at, roles, name, created_at, updated_at, authCode, twoFactorAuthentication FROM __temp__user;
```

2021-01-21 08:43 UTC, j0k3r commented on en/admin/query-upgrade-23-24.md
> +CREATE TABLE wallabag_config (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, theme VARCHAR(255) NOT NULL COLLATE BINARY, items_per_page INTEGER NOT NULL, language VARCHA
```suggestion
CREATE TABLE wallabag_config (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, user_id INTEGER DEFAULT NULL, theme VARCHAR(255) NOT NULL COLLATE BINARY, items_per_page INTEGER NOT NULL, language VARCHAR(255) NOT NULL COLLATE BINARY, reading_speed DOUBLE PRECISION DEFAULT NULL, pocket_consumer_key VARCHAR(255) DEFAULT NULL COLLATE BINARY, action_mark_as_read INTEGER DEFAULT 0, list_mode INTEGER DEFAULT NULL, feed_token VARCHAR(255) DEFAULT NULL, feed_limit INTEGER DEFAULT NULL, CONSTRAINT FK_87E64C53A76ED395 FOREIGN KEY (user_id) REFERENCES "wallabag_user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE);
```

2021-01-21 17:38 UTC, jonathansada commented
Fixed errors

2021-01-22 09:29 UTC, nicosomb approved these changes

2021-01-25 08:16 UTC, j0k3r approved these changes
👍

2021-01-25 08:17 UTC, merged